language: php

php:
  - 7.2

before_install:
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "5.6" ]]; then composer require --dev --no-update phpunit/phpunit 5.7.5; fi

before_script:
  - mysql -e 'create database homestead_test;'
  - composer self-update
  - composer install --no-interaction

script:
- vendor/bin/phpunit